version: '3'

services:
  vnc-chromium:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chromium-test
    ports:
      - "6080:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - CHROME_CLI=https://www.google.com/
      - LC_ALL=zh_CN.UTF-8
      - TITLE=Chromium
      - PASSWORD=1234
    volumes:
      - ./config:/config
    shm_size: "1gb"
    restart: unless-stopped
