version: '3'

services:
  vnc-chromium:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chromium-test
    ports:
      - "6080:6080"
    environment:
      - WINDOW_SIZE=1920x1080
      - VNC_PASS=1234
    volumes:
      - ./data:/data
