version: '3'

services:
  vnc-chromium:
    build: .
    image: vnc-chromium
    container_name: chromium-test
    ports:
      - "6080:6080"
    environment:
      - WINDOW_SIZE=1920x1080
      - VNC_PASS=1234
    volumes:
      - ./data:/data
